### ISSUE TITLE
AWS GovCloud Support

### ISSUE THREAD

**Issue by aalbertson** [pwae/aws-sso-colourise#1]
It would be nice if you had AWS GovCloud AWS SSO support builtin.

I took an initial stab at it, and adding the following seemed to partially work, but there was a strange bug related to querying the local storage:

	"host_permissions": [
		"*://*.console.aws.amazon.com/*",
		"*://*.console.amazonaws-us-gov.com/*"
	],
	"content_scripts": [
		{
		  "matches": ["*://*.console.aws.amazon.com/*", "*://console.amazonaws-us-gov.com/*"],
		  "js": ["main.js"]
		}
	]

I was at a loss trying to figure out what the bug was, so I figured I'd just leave this to you and see if you can sort it. Happy to help test!

**Comment by pwae** [comment]
I've made some changes in #2 to hopefully fix the errors, but also add the gov cloud domains.
If you want to pull the latest git repo down and test that locally - would be good (it's in master).

Otherwise, 1.3.0 should be available on the chrome web extension store, as soon as it's approved.

**Comment by pwae** [comment]
It's live now. Will close this. feel free to re-open if you have any issues still! :)
